# Generated by Django 5.1.1 on 2025-01-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdb',
            name='feedback',
            field=models.CharField(max_length=400),
        ),
    ]
