# Generated by Django 5.1.1 on 2025-01-15 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0003_recipesdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('dishname', models.CharField(max_length=20)),
                ('recipe', models.TextField(max_length=500)),
                ('time_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='RecipesDb',
        ),
    ]
