# Generated by Django 5.1.1 on 2025-01-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0005_recipesdb_delete_recipedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesdb',
            name='recipe',
            field=models.TextField(),
        ),
    ]
